import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import fetch from "isomorphic-unfetch";
import { Button, Popup } from "semantic-ui-react";

export default function Home({ notes }) {
  const [myNotes, setMyNotes] = useState(notes);
  const handleDeleteClick = async (id) => {
    await fetch(`http://localhost:3000/api/notes/${id}`, {
      method: "DELETE",
    });
    const newNotes = await fetch("http://localhost:3000/api/notes");
    const { data } = await newNotes.json();
    setMyNotes(data);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to NotEd</h1>

        {myNotes.map((note) => (
          <div key={note._id} onClick={() => handleDeleteClick(note._id)}>
            <Popup
              content="Click for delete"
              trigger={
                <Button style={{ backgroundColor: "white" }}>
                  <h3>{note.title}</h3>
                  <p>{note.description}</p>
                </Button>
              }
            />
          </div>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="http://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

Home.getInitialProps = async () => {
  const res = await fetch("http://localhost:3000/api/notes");
  const { data } = await res.json();
  return { notes: data };
};
